// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6YqKjiaVrgSowqyDt0saxhcxgIRreig',
    appId: '1:1088757635375:web:ee53753e46b244e248a9da',
    messagingSenderId: '1088757635375',
    projectId: 'befit-573a3',
    authDomain: 'befit-573a3.firebaseapp.com',
    storageBucket: 'befit-573a3.firebasestorage.app',
    measurementId: 'G-DWN2JVL85S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYkEAsL6vit7gQ2RA_XiY971rFO8YJyiM',
    appId: '1:1088757635375:android:f33446aac382d05b48a9da',
    messagingSenderId: '1088757635375',
    projectId: 'befit-573a3',
    storageBucket: 'befit-573a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCag7Ww-0aiJOqQU18cuOCWiZmRFH7rmzU',
    appId: '1:1088757635375:ios:7829bd6201268eff48a9da',
    messagingSenderId: '1088757635375',
    projectId: 'befit-573a3',
    storageBucket: 'befit-573a3.firebasestorage.app',
    iosBundleId: 'com.example.befit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCag7Ww-0aiJOqQU18cuOCWiZmRFH7rmzU',
    appId: '1:1088757635375:ios:7829bd6201268eff48a9da',
    messagingSenderId: '1088757635375',
    projectId: 'befit-573a3',
    storageBucket: 'befit-573a3.firebasestorage.app',
    iosBundleId: 'com.example.befit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM6YqKjiaVrgSowqyDt0saxhcxgIRreig',
    appId: '1:1088757635375:web:0dd1b264c353dd4e48a9da',
    messagingSenderId: '1088757635375',
    projectId: 'befit-573a3',
    authDomain: 'befit-573a3.firebaseapp.com',
    storageBucket: 'befit-573a3.firebasestorage.app',
    measurementId: 'G-YNM2TRGC54',
  );

}